### ISSUE TITLE
How to call `Context::new` safely?

### ISSUE THREAD

**Issue by gaetanww** [parallaxsecond/rust-tss-esapi#229]
The docs for the method `Context::new` states:
     
            * the client is responsible for ensuring that the context can be initialized safely, threading-wise
      
How do we make sure the call is safe? If we have a multithreaded application, should we make sure that only one `Context` is created at a time? 

The way I understand the [ESAPI specs](https://trustedcomputinggroup.org/wp-content/uploads/TSS_TSS-2.0-Enhanced-System-API_V0.9_R03_Public-Review-1.pdf) (see below), `esys_initialize` should always be safe to call, but the same `ESYS_CONTEXT` object must not be shared between threads. 

> State information is stored in contexts provided to the application. These ESAPI contexts areaccessible simultaneously. No two threads are allowed the same ESAPI context simultaneously.

**Comment by ionut-arm** [comment]
Hey!

If I remember correctly, the issue was actually down to the layers below the ESAPI, more precisely around TPM Access Broker/Resource Manager (TABRM). In some cases, I think, there is no TABRM between applications and the TPM, meaning there can only be one active context at any time. 

That's why, for example, we run test in a [single-threaded way](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/tests/all-ubuntu.sh#L33), since each test opens its own context - because we don't use a TABRM between the tests and the software TPM.

We could enhance our tests to run both with and without a broker in between to make sure it does work like that. I'll do a small test locally, just to make sure, will report back :) 

> These ESAPI contexts are accessible simultaneously. No two threads are allowed the same ESAPI context simultaneously.

This one is actually taken care of by our methods on `Context` - because you need a mutable reference to make any calls, you're only able to call from a single-threaded app, or by adding locking around the places where such calls happen.

**Comment by gaetanww** [comment]
Thanks for your reply!

> If I remember correctly, the issue was actually down to the layers below the ESAPI, more precisely around TPM Access Broker/Resource Manager (TABRM). In some cases, I think, there is no TABRM between applications and the TPM, meaning there can only be one active context at any time.

Does that mean there are race conditions in the SAPI when not using a resource broker? Or is it just that the TPM interactions might fail in unexpected ways, because there are state inconsistencies?

**Comment by ionut-arm** [comment]
It seems that line was added in response to [this](https://github.com/parallaxsecond/rust-tss-esapi/issues/7). I guess you can call them race conditions, the [TABRM spec](https://trustedcomputinggroup.org/wp-content/uploads/TSS_2p0_TAB_ResourceManager_v1p0_r18_04082019_pub.pdf) says:
```
The TPM access broker (TAB) handles multi-process synchronization to the TPM.  A process accessing the TPM can be guaranteed that it will be able to complete a TPM command without interference from other competing processes.
```

We made `new` unsafe mostly because we weren't sure we could guarantee, from within the library, if the created `Context` is safe to use as it seems to depend on the environment (if there's a TABRM, if multiple processes/threads are attempting to create contexts, etc).

**Comment by gaetanww** [comment]
Thanks for your reply.

Let me clarify my comment. I believe the `unsafe` annotation is not justified here. The `unsafe` keyword [refers specifically to memory safety](https://doc.rust-lang.org/std/keyword.unsafe.html). The problem that would arise from using this method incorrectly are not of memory safety but that some TPM commands would fail unexpectedly. Thus it is breaking rust semantic to use this keyword here. 

However, I understand the interest to let the user know that this method should be called correctly. Maybe there could be two different functions to instantiate a `Context` struct:
1) `Context::new` for instantiating with the TABRM TCTI.
2) `Context::with_unchecked_concurrent_access` for the other TCTIs. 
Obviously the naming is not great, but it could be improved.

**Comment by ionut-arm** [comment]
Hey, sorry for the delay.

That page is a bit weird, because it claims that `unsafe` is only about memory, yet it says just below, in bold, that:
> No matter what, Safe Rust can’t cause Undefined Behavior.

It's also strange that only that first line mentions "memory", whereas the following paragraph mentions "contracts" in general, under which I'd put interaction with external libraries and entities in the environment. For example, the Rustonomicon [says](https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html):
> On functions, `unsafe` means that users of the function must check that function's documentation to ensure they are using it in a way that maintains the contracts the function requires.

> are not of memory safety but that some TPM commands would fail unexpectedly.

If that was the case we'd simply return an error from `new`, but the problem is that the program hangs and that's outside of our control. An option would be to create another function as you suggested, though changing the interface of `new` would break our current API (and would be less generic than `new` implies), so I'd lean towards `new_over_tabrm`, or something of that sort.

**Comment by gaetanww** [comment]
> If that was the case we'd simply return an error from new, but the problem is that the program hangs and that's outside of our control. An option would be to create another function as you suggested, though changing the interface of new would break our current API (and would be less generic than new implies), so I'd lean towards new_over_tabrm, or something of that sort.

Sounds like a great solution. It would have the added benefit of pushing users towards using the resource manager. 

> It's also strange that only that first line mentions "memory", whereas the following paragraph mentions "contracts" in general, under which I'd put interaction with external libraries and entities in the environment.

This page does not seem to define contract. However, the reference [equates it to non-undefined behaviour](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#undefined-behavior) relative to the Rust abstract machine. A list of [actions causing undefined behaviour can be found in the Rustonimicon](https://doc.rust-lang.org/nomicon/what-unsafe-does.html) which are the "contracts" the caller code of unsafe must uphold.

**Comment by ionut-arm** [comment]
Hmm, indeed, and it does seem to mention deadlocks as _not_ being "unsafe" events. I'll have to read up on what the actual risk is when trying to open multiple contexts when you don't have an ABRM - can you get some sort of "pollution" between them?

**Comment by gaetanww** [comment]
This [spec would be relevant](https://trustedcomputinggroup.org/wp-content/uploads/TSS-TAB-and-Resource-Manager-ver1.0-rev16_Public_Review.pdf) especially section 2.3.

**Comment by gaetanww** [comment]
I don’t think #239 solves this issue entirely. It may be possible to call “Context::new” safely (in the Rust meaning of safe). We could still consider whether to remove “unsafe” for this method.

**Comment by gaetanww** [comment]
> Hmm, indeed, and it does seem to mention deadlocks as _not_ being "unsafe" events. I'll have to read up on what the actual risk is when trying to open multiple contexts when you don't have an ABRM - can you get some sort of "pollution" between them?

The main risk is the disordering of commands:
- sequence of commands to the TPM is interrupted by another application and commands fail unexpectedly. (Mentioned in spec above). In particular, commands for context management, you might flush the TPM context of another application, or have key slots filled by another application while using the TPM.
In the Rust sense, it is not a safety issue.

**Comment by hug-dev** [comment]
Ok I will open a PR to remove the `unsafe` and add those notes as a warning
