### ISSUE TITLE
Verify the TPM signature using OpenSSL

### ISSUE THREAD

**Issue by DNJha** [parallaxsecond/rust-tss-esapi#384]
Hi,

I want to verify a signature generated by TPM using OpenSSL.

To do this, I'm importing my external key to the TPM (`load_external`) and signing a test data (`sign`). When I'm checking, the TPM-generated signature is very different from the one generated with OpenSSL. 

As I'm sending the signature to another machine not having TPM, I want to verify the same using the public key and OpenSSL. Can you please suggest to me some way to achieve this?

Thank you.

**Comment by ionut-arm** [comment]
Hey,

A few questions:

* what kind of key (and signing scheme) are you using? RSA/ECC...?
* when you say "when I'm checking" - what is your process for looking at the signature? Do you marshall it?

I think the reason you're seeing that discrepancy is because what you get from the TPM is a TPM-specific structure - [`TPMT_SIGNATURE`](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/src/structures/tagged/signature.rs#L19) to be more precise - whose serialization is quite different from a "normal" signature like what OpenSSL would output. If you want to see some example code doing a conversion between the two, look at the Parsec code that does exactly this, [here](https://github.com/parallaxsecond/parsec/blob/main/src/providers/tpm/utils.rs#L363). RSA signatures are quite straightforward, but for ECC you'll need to do some conversion "by hand" :)

**Comment by DNJha** [comment]
Hi @ionut-arm,

Thanks for your reply. I thought the same. I'm using an RSA key and I'm parsing the signature to get the value.

However, I'm using my own key (PEM file) using [load_external](https://github.com/parallaxsecond/rust-tss-esapi/blob/4620f3f140652675351d6793fd085e62b2b95d76/tss-esapi/src/context/tpm_commands/object_commands.rs#L133) (loading the key components n and q) and get a handle. The signature is generated with this handle and test data.

I'm not sure, what I'm doing wrong but the signature value does not match with the value generated using OpenSSL. I'm struggling to find the reason but haven't managed to. The only reason I can think about is the load_external function. 

Any suggestion is much appreciated. Thank you.

**Comment by Superhepper** [comment]
What does the TPM 2.0 specification say about the signature that is being generated?

**Comment by DNJha** [comment]
The TPM 2.0 specification states the signature generated is of TPM-specific structure (TPMT_SIGNATURE) which for the RSA algorithm is simple to extract as answered [here](https://github.com/parallaxsecond/rust-tss-esapi/issues/384#issuecomment-1351657631).

I've tested that with [IBM's TPM2.0 TSS](https://sourceforge.net/projects/ibmtpm20tss/) previously when I was loading my key with `import_pem` and generating a signature with the TPM handle and later validating the same with the OpenSSL. 

I want to do the same here. Since the `import_pem` function is not directly available yet, I got the suggestion to use the  `load_external` and generate the signature.

**Comment by Superhepper** [comment]
I would make sure that the padding (i.e. RSAPSS or RSASSA) and the hashing algorithm match.

**Comment by ionut-arm** [comment]
So is the problem here that the formatting differs - the TPM gives you some TPM-specific stuff, while OpenSSL expects some other format - or is it that even after you account for the format difference you get something weird? Not sure the way you get the key in the TPM is necessarily relevant - if you can sign, that should be good enough.

I agree with @Superhepper - worth checking the scheme. Also, some of the schemes are probabilistic, so you'll always get a different value, but I'm assuming that's not the relevant point here. 

Maybe sharing a code snippet would help.

**Comment by ionut-arm** [comment]
Ok, right, it seems the problem is with the definitions of the two signature operations. The [OpenSSL call](https://docs.rs/openssl/latest/src/openssl/sign.rs.html#329-339) hashes the data you put in before signing, while our [TSS call](https://docs.rs/tss-esapi/7.1.0/src/tss_esapi/context/tpm_commands/signing_and_signature_verification.rs.html#45-74). I checked this by taking your example and adding a hashing step to `DATA_VEC` just before calling the `context.sign` and then got two identical signatures. So the solution is to make the OpenSSL operations directly on the data you wish to sign/verify, rather than on its digest.
