### ISSUE TITLE
Feature API compliance

### ISSUE THREAD

**Issue by genofire** [parallaxsecond/rust-tss-esapi#61]
I ask myself, if this Projekt want to be compliane with the [TCG Feature API](https://trustedcomputinggroup.org/wp-content/uploads/TSS_FAPI_v0.94_r04_pubrev.pdf).

It is not released yet (https://trustedcomputinggroup.org/resource/tss-feature-api-specification/), but we could try it with the draft (first link).

**Comment by ionut-arm** [comment]
Indeed, we started this project because the FAPI wasn't available when we needed something of that kind. We could go the way of implementing the FAPI functionality here, but that feels somewhat useless. A better approach would be to create yet another crate that does the FFI bindings to FAPI and create an ergonomic Rust wrapper around that.

However, as you mentioned, the FAPI specification isn't stable yet - I'm not really sure when it would be (maybe it is actually stable but they're just not sure if they want to change anything, I really have no clue). This makes it tricky to support for now and if you do go and put some work into making a Rust wrapper, you might find yourself chasing some moving specs.

That being said, we might decide in the future that we'd rather implement our own functionality (the TPM provider within the [Parsec ](https://github.com/parallaxsecond/parsec) project) on top of the new FAPI instead of the ESAPI - that would make a lot of sense, since we have no need to do our own session handling, for example. So maybe in the future we'll decide to create a wrapper around that too! But this repo will remain focused on ESAPI, simply to keep it clear-cut and contained!
